### PR TITLE
Update remote visualisation Workflow 

### PR DESCRIPTION
**Pull request by MaelAudren**
- Instead of waiting 1000 seconds to end the task, the remote visualization will stop after 120 seconds.
- The remote visualization and the task can be stopped manually by pressing the "q" button on the keyboard.

### CODE REVIEW

**Comment by lpellegr** [comment]
@MaelAudren Is there a system test to ensure this Workflow works as expected?

**Comment by MaelAudren** [comment]
@lpellegr It seems that the only test related to the task is about the name and the order of the task among others tasks and I didn't change those values.

**Comment by lpellegr** [comment]
@MaelAudren yes sure, that's why it's maybe the right time to add a system test for this Workflow if none are present?

**Comment by MaelAudren** [comment]
@lpellegr The workflow is related to remote visualisation. I think that adding test that ensure that the workflow it working well would be out off scope or too much work concerning the card.

**Comment by lpellegr** [comment]
OK, as you want. As consequence, it will not be possible to detect regressions on such example.

**Pull request merged**
