### PR TITLE
Fix SQL error on shutdown when embedded HSQLDB server is used

### PR DESCRIPTION
**Pull request by lpellegr**
The default embedded database must not be closed in a shutdown hook.

Multiple shutdown hooks are defined. Some are used for instance by the
Resource Manager to remove node sources before termination. If the database is
closed before completing the last operation, then some errors will occur
(see logs).

Besides, checking the state of the Scheduler and RM by registering an event
listener or even by polling with periodic method calls will not work since
Scheduler and RM are Active Objects and these are terminated by other shutdown
hooks.

The database connection should be closed by Hibernate when the datasource is
closed. If not, the HSQLDB server will handle in the worst case the JVM shutdown
as an accidental machine failure.

### CODE REVIEW

**Comment by lpellegr** [comment]
@ow2-proactive/developers Could 2 people please review the changes?

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 1 issue

1. MAJOR [SchedulerStarter.java#L322](https://github.com/ow2-proactive/scheduling/blob/03667d7c82cb11fe30ba34a00db496abd9b4e161/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/util/SchedulerStarter.java#L322): Reduce this anonymous class number of lines from 26 to at most 20, or make it a named class. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1188)

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 1 issue

1. MAJOR [SchedulerStarter.java#L322](https://github.com/ow2-proactive/scheduling/blob/34734e513beaaa2836882c4e2314c769c785adf1/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/util/SchedulerStarter.java#L322): Reduce this anonymous class number of lines from 26 to at most 20, or make it a named class. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1188)

**Comment by yinan-liu** [comment]
i was thinking the issue happened only on server mode, not on embedded file mode (as it has never had such issue before), so why remove it completely even for embedded mode ? if we dont close it, what will happen on embedded file mode?

**Comment by lpellegr** [comment]
@yinan-liu If you look at the implementation of [SchedulerHsqldbStarter](https://github.com/lpellegr/scheduling/blob/34734e513beaaa2836882c4e2314c769c785adf1/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/util/SchedulerHsqldbStarter.java) you will see that `hsqldbServer.stop();` is doing something when HSQLDB server is used only. In that case, I still call it _embedded_ since this mode is the one enabled by default in the Scheduler without any additional configuration. If HSQLDB file mode is configured in configuration files of the Scheduler and/or RM, then the behaviour is exactly the same as in 7.19.X and below.

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 1 issue

1. MAJOR [SchedulerStarter.java#L322](https://github.com/ow2-proactive/scheduling/blob/5c040d9dd7b3ead5269074b24169d939742cc7ac/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/util/SchedulerStarter.java#L322): Reduce this anonymous class number of lines from 26 to at most 20, or make it a named class. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1188)

**Pull request merged**
