### PR TITLE
fix1997

### LINKED ISSUE #1997: Tasks from a loop with a lot of tasks cannot be retrieved
<a href="https://jira.activeeon.com/browse/SCHEDULING-2234" title="SCHEDULING-2234">Original issue</a> created by <a href="mailto:youri.bonnaffe_AT_activeeon.com">Youri Bonnaffe</a> on 03, Mar 2015 at 09:12 AM - SCHEDULING-2234

<hr />

When running a workflow with a loop that loops forever, at some point the tasks cannot be retrieved in Scheduler portal or REST API.
Here the loop produced more than 1500 tasks.

jobstate(jobid) will produce: _Error Message: java.lang.StackOverflowError cannot be cast to java.lang.Exception_

Full stack trace is available in stacktrace.txt file.

### PR DESCRIPTION
**Pull request by tobwiens**
This fixes #1997.

### CODE REVIEW

**Comment by tobwiens** [comment]
This is linked to #2326 and #1997.

**Comment by tobwiens** [comment]
Can two @ow2-proactive/developers please review.

**Comment by marcocast** [comment]
:+1:

**Comment by paraita** [comment]
:white_check_mark:

**Comment by tobwiens** [comment]
Retest this please.

**Comment by tobwiens** [comment]
Retest this please.

**Pull request merged**
