### PR TITLE
Make VFSZipper.ZIP able to unzip a file hierarchy

### PR DESCRIPTION
**Pull request by lpellegr**
This patch fixes ow2-proactive/issues#2659.

### CODE REVIEW

**Comment by lpellegr** [comment]
Retest this please.

**Comment by fviale** [comment]
:+1:

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Pull request merged**
