### PR TITLE
StaxJobFactory assumes attributes are encountered in a given order

### PR DESCRIPTION
**Pull request by lpellegr**

### CODE REVIEW

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
@fviale Thank you for the review. I have restored `CommonAttribute#getGenericInformations` but marked it as deprecated so that it can be removed smoothly in the future.

**Comment by fviale** [comment]
Thanks Laurent !

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Pull request merged**
