### PR TITLE
improve email template - add job id in the body and remove the version

### PR DESCRIPTION
**Pull request by sophiesongge**

### CODE REVIEW

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [JobEmailNotification.java#L12](https://github.com/ow2-proactive/scheduling/blob/7f919e8344f818f5a073dbc95d196abffab06e8a/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/JobEmailNotification.java#L12): Remove this unused import 'org.ow2.proactive.scheduler.common.Main'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by sophiesongge** [comment]
retest this please

**Comment by sophiesongge** [comment]
retest this please

**Comment by sophiesongge** [comment]
retest this please

**Comment by sophiesongge** [comment]
@tobwiens I randomly got this test failed: SelectionUtilsTest.checkOSName

Can we skip this test just for now? Because this PR is blocked for 2 days, once I randomly passed the jenkins test, then it asked me to "Update branch", after the update the test kept failing T^T

**Comment by sophiesongge** [comment]
retest this please

**Pull request merged**
