### PR TITLE
Remove tools/proactive-server-script

### LINKED ISSUE #2285: Remove tools/proactive-server-script
This script should no longer be used. Besides, it leads to confusion.

Related files should also be removed, such as `tools/startup.groovy`.

### PR DESCRIPTION
**Pull request by lpellegr**
This patch closes #2285.

### CODE REVIEW

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
@ow2-proactive/developers Could one more person please review the changes?

**Comment by paraita** [comment]
didn't see anything wrong

**Pull request merged**
