### PR TITLE
Enhancements for using the Scheduler in production

### PR DESCRIPTION
**Pull request by lpellegr**
WIP do not merge

Current changes:

- Move credentials to a dedicated folder
- Use 2048 bits as default key size for encrypting with RSA
- Add Gradle task that copies required files just in time to prevent duplicated files
- Introduce new group and user allowed to add node only to RM
- Remove rm.cred from node.jar

Actions: 

  - See Trello card 
  - Investigate why removing rm.cred cause problem even if node.cred are in place and are ok (cf. commit 1bec0aa)
  - Rebase on master
  - Apply the same to pull-requests that are associated in others projects

### CODE REVIEW

**Comment by lpellegr** [comment]
Retest this please.

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [RMStateCaching.java#L131](https://github.com/ow2-proactive/scheduling/blob/ffe2dfd33cf3214d0b6c650a58840b79f65ceba1/rest/rest-server/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/RMStateCaching.java#L131): Reduce this anonymous class number of lines from 22 to at most 20, or make it a named class. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1188)

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [RMStateCaching.java#L131](https://github.com/ow2-proactive/scheduling/blob/1bec0aa0f50723d60520b0568f907468c49a4f51/rest/rest-server/src/main/java/org/ow2/proactive_grid_cloud_portal/rm/RMStateCaching.java#L131): Reduce this anonymous class number of lines from 22 to at most 20, or make it a named class. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1188)

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Pull request closed without merging**
