### PR TITLE
Improvements and fixes related to RM unresponsive issue

### PR DESCRIPTION
**Pull request by lpellegr**
Port changes from the 7.19.X branch.

### CODE REVIEW

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 3 issues

1. MAJOR [InfrastructureManager.java#L401](https://github.com/ow2-proactive/scheduling/blob/9f658448baf0310d614c7d4a9ae76e5ba4a40c0a/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/nodesource/infrastructure/InfrastructureManager.java#L401): Remove this unused method parameter "proactiveProgrammingNode". [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1172)
1. MINOR [RMNodeStarter.java#L146](https://github.com/ow2-proactive/scheduling/blob/9f658448baf0310d614c7d4a9ae76e5ba4a40c0a/rm/rm-node/src/main/java/org/ow2/proactive/resourcemanager/utils/RMNodeStarter.java#L146): Reorder the modifiers to comply with the Java Language Specification. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)
1. MINOR [InfrastructureManager.java](https://github.com/ow2-proactive/scheduling/blob/9f658448baf0310d614c7d4a9ae76e5ba4a40c0a/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/nodesource/infrastructure/InfrastructureManager.java): Replace all tab characters in this file by sequences of white-spaces. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS00105)

**Comment by lpellegr** [comment]
Retest this please.

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 1 issue

1. MINOR [RMNodeStarter.java#L146](https://github.com/ow2-proactive/scheduling/blob/072ea13cb4b0243efb4e73cf7cc2c67eaee8cb05/rm/rm-node/src/main/java/org/ow2/proactive/resourcemanager/utils/RMNodeStarter.java#L146): Reorder the modifiers to comply with the Java Language Specification. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)

**Comment by lpellegr** [comment]
Retest this please.

**Pull request merged**
