### PR TITLE
Decouple Job ID from Task ID

### PR DESCRIPTION
**Pull request by lpellegr**

### CODE REVIEW

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by fviale** [comment]
One important thing to consider regarding the decoupling of taskids from jobids is log output.

Currently the node logs are configured to prepend the taskid in all output coming from a given task.

This id was sufficient to identify the task as the job id was embedded.

With the decoupling, it will be necessary to add the jobid as an extra information to the node log output.

**Comment by lpellegr** [comment]
Thank you Fabien. I will consider your suggestions.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Pull request closed without merging**
