### PR TITLE
Add database configuration file examples

### PR DESCRIPTION
**Pull request by lpellegr**
Samples include MariaDB, MySQL, PostgreSQL and SQL Server.

### CODE REVIEW

**Comment by fviale** [comment]
sql-server maybe ?

**Comment by lpellegr** [comment]
@fviale I have added for SQL Server. However, the configuration file was not tested.

**Comment by fviale** [comment]
@lpellegr, thanks, testing it requires a licence indeed

**Comment by lpellegr** [comment]
Retest this please.

**Pull request merged**
