### PR TITLE
Update copyright year

### LINKED ISSUE #2010: Update copyright year
<a href="https://jira.activeeon.com/browse/SCHEDULING-2247" title="SCHEDULING-2247">Original issue</a> created by <a href="mailto:youri.bonnaffe_AT_activeeon.com">Youri Bonnaffe</a> on 26, Mar 2015 at 16:52 PM - SCHEDULING-2247

<hr />

Especially where visible (for instance get started page)

### PR DESCRIPTION
**Pull request by lpellegr**
Linked with https://github.com/ow2-proactive/scheduling-portal/pull/241.

This pull-request closes #2010.

### CODE REVIEW

**Comment by lpellegr** [comment]
@ow2-proactive/developers Could two people please review the changes?

**Comment by tobwiens** [comment]
:+1:
Good that you automated it for the getstarted page :+1:

**Comment by lpellegr** [comment]
Thank you Tobias, could one more person please review the changes?

**Comment by cdiop** [comment]
Perfect

**Comment by lpellegr** [comment]
Ok, thanks!

**Pull request merged**
