### PR TITLE
Topology use hostname instead of InetAddress

### PR DESCRIPTION
**Pull request by fviale**
InetAddress was used as key to several maps.

This does not work properly as InetAddress are equals if their associated ipv4 address are equals thus 127.0.1.1 from different hosts are considered equals.

Instead of using InetAddress, we now use hostnames.

### CODE REVIEW

**Comment by nebilbenmabrouk** [comment]
@fviale a global comment. What if different machines (with different IPs) have the same hostname? (like our trydev and jenkins)
I suggest to compare nodes using both **hostname** and **InetAddress**, thus, we obtain reliable comparisons.
What do you think?

**Comment by fviale** [comment]
@nebilbenmabrouk and what if multiples nodes are deployed on the same machine but bound to different ip addresses (network interface) ?
There is no perfect solution here. and I prefer to consider multiple machines with the same hostname an infrastructure and not a proactive issue.

**Comment by nebilbenmabrouk** [comment]
> @nebilbenmabrouk and what if multiples nodes are deployed on the same machine but bound to different ip addresses (network interface) ?
> There is no perfect solution here. and I prefer to consider multiple machines with the same hostname an infrastructure and not a proactive issue.

Fair enough :)

**Review by nebilbenmabrouk — APPROVED** [review]
LGTM

**Review by mboussaa — APPROVED** [review]

**Pull request merged**
