### PR TITLE
Replace existing template for variables propagation by a new one

### PR DESCRIPTION
**Pull request by lpellegr**
The purpose of the new template is to demonstrate variables usage. It receives
as input a number of light bulbs, their coverage angle (in degrees) and the
expected coverage. In output the worflow check if their is enough bulbs to reach
the expectation.

This patch fixes ow2-proactive/studio#213.

### CODE REVIEW

**Comment by lpellegr** [comment]
@ow2-proactive/developers Could two people please review the changes?

**Comment by paraita** [comment]
:+1:

**Comment by cdiop** [comment]
Oki for me

**Comment by tobwiens** [comment]
Is ok.

**Comment by lpellegr** [comment]
Thank you for the reviews.

**Pull request merged**
