### PR TITLE
#2879 : Memory Leak : LOG4J Hierarchy keeps a Hashtable of all dynamic job loggers without any cleaning strategy

### PR DESCRIPTION
**Pull request by fviale**
Use Java reflection to manually remove job logger from the Hashtable when the job is terminated

### CODE REVIEW

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 3 issues

1. MAJOR [LoggingEventProcessor.java#L71](https://github.com/ow2-proactive/scheduling/blob/313ae65e1ac577ec23b8364231f8e7c3a0b96456/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/LoggingEventProcessor.java#L71): Replace the synchronized class "Hashtable" by an unsynchronized one such as "HashMap". [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1149)
1. MINOR [LoggingEventProcessor.java#L29](https://github.com/ow2-proactive/scheduling/blob/313ae65e1ac577ec23b8364231f8e7c3a0b96456/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/LoggingEventProcessor.java#L29): Remove this unused import 'java.util.Arrays'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [LoggingEventProcessor.java#L43](https://github.com/ow2-proactive/scheduling/blob/313ae65e1ac577ec23b8364231f8e7c3a0b96456/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/LoggingEventProcessor.java#L43): Make the "logger" logger private static final. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1312)

**Comment by fviale** [comment]
Retest this please

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 17 issues
* MAJOR 7 major
* MINOR 10 minor

#### Top 10 issues

1. MAJOR [Log4JRemover.java#L42](https://github.com/ow2-proactive/scheduling/blob/094dbcd85750f3e6af7c314ae12ecb82db4f81c2/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L42): Add a private constructor to hide the implicit public one. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1118)
1. MAJOR [Log4JRemover.java#L61](https://github.com/ow2-proactive/scheduling/blob/094dbcd85750f3e6af7c314ae12ecb82db4f81c2/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L61): Introduce a new variable instead of reusing the parameter "hierarchy". [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1226)
1. MAJOR [Log4JRemover.java#L67](https://github.com/ow2-proactive/scheduling/blob/094dbcd85750f3e6af7c314ae12ecb82db4f81c2/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L67): Replace the synchronized class "Hashtable" by an unsynchronized one such as "HashMap". [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1149)
1. MAJOR [LoggingEventProcessor.java#L69](https://github.com/ow2-proactive/scheduling/blob/094dbcd85750f3e6af7c314ae12ecb82db4f81c2/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/LoggingEventProcessor.java#L69): Replace the synchronized class "Hashtable" by an unsynchronized one such as "HashMap". [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1149)
1. MAJOR [LoggingEventProcessor.java#L69](https://github.com/ow2-proactive/scheduling/blob/094dbcd85750f3e6af7c314ae12ecb82db4f81c2/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/LoggingEventProcessor.java#L69): Remove this unused "loggersTable" private field. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1068)
1. MAJOR [TaskLogger.java#L82](https://github.com/ow2-proactive/scheduling/blob/094dbcd85750f3e6af7c314ae12ecb82db4f81c2/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L82): Rename field "taskLogger" [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1700)
1. MAJOR [TaskLogger.java#L102](https://github.com/ow2-proactive/scheduling/blob/094dbcd85750f3e6af7c314ae12ecb82db4f81c2/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L102): Rename "taskLogger" which hides the field declared at line 82. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. MINOR [Log4JRemover.java#L44](https://github.com/ow2-proactive/scheduling/blob/094dbcd85750f3e6af7c314ae12ecb82db4f81c2/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L44): Make the "logger" logger private static final. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1312)
1. MINOR [LoggingEventProcessor.java#L28](https://github.com/ow2-proactive/scheduling/blob/094dbcd85750f3e6af7c314ae12ecb82db4f81c2/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/LoggingEventProcessor.java#L28): Remove this unused import 'java.lang.reflect.Field'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [LoggingEventProcessor.java#L29](https://github.com/ow2-proactive/scheduling/blob/094dbcd85750f3e6af7c314ae12ecb82db4f81c2/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/LoggingEventProcessor.java#L29): Remove this unused import 'java.util.Arrays'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 18 issues
* MAJOR 5 major
* MINOR 13 minor

#### Top 10 issues

1. MAJOR [Log4JRemover.java#L42](https://github.com/ow2-proactive/scheduling/blob/5bae533a6cacc0d7dd460797eda2b2c3ee8e5e53/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L42): Add a private constructor to hide the implicit public one. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1118)
1. MAJOR [Log4JRemover.java#L61](https://github.com/ow2-proactive/scheduling/blob/5bae533a6cacc0d7dd460797eda2b2c3ee8e5e53/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L61): Introduce a new variable instead of reusing the parameter "hierarchy". [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1226)
1. MAJOR [Log4JRemover.java#L67](https://github.com/ow2-proactive/scheduling/blob/5bae533a6cacc0d7dd460797eda2b2c3ee8e5e53/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L67): Replace the synchronized class "Hashtable" by an unsynchronized one such as "HashMap". [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1149)
1. MAJOR [TaskLogger.java#L82](https://github.com/ow2-proactive/scheduling/blob/5bae533a6cacc0d7dd460797eda2b2c3ee8e5e53/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L82): Rename field "taskLogger" [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1700)
1. MAJOR [TaskLogger.java#L102](https://github.com/ow2-proactive/scheduling/blob/5bae533a6cacc0d7dd460797eda2b2c3ee8e5e53/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L102): Rename "taskLogger" which hides the field declared at line 82. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. MINOR [Log4JRemover.java#L44](https://github.com/ow2-proactive/scheduling/blob/5bae533a6cacc0d7dd460797eda2b2c3ee8e5e53/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L44): Make the "logger" logger private static final. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1312)
1. MINOR [TaskLogger.java#L31](https://github.com/ow2-proactive/scheduling/blob/5bae533a6cacc0d7dd460797eda2b2c3ee8e5e53/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L31): Remove this unused import 'java.lang.reflect.Constructor'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [TaskLogger.java#L32](https://github.com/ow2-proactive/scheduling/blob/5bae533a6cacc0d7dd460797eda2b2c3ee8e5e53/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L32): Remove this unused import 'java.lang.reflect.Field'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [TaskLogger.java#L33](https://github.com/ow2-proactive/scheduling/blob/5bae533a6cacc0d7dd460797eda2b2c3ee8e5e53/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L33): Remove this unused import 'java.util.Hashtable'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [TaskLogger.java#L39](https://github.com/ow2-proactive/scheduling/blob/5bae533a6cacc0d7dd460797eda2b2c3ee8e5e53/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L39): Remove this unused import 'org.apache.log4j.Hierarchy'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 19 issues
* MAJOR 6 major
* MINOR 13 minor

#### Top 10 issues

1. MAJOR [Log4JRemover.java#L42](https://github.com/ow2-proactive/scheduling/blob/e06826a5ae9bf38c3a462a031662b49109d0757f/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L42): Add a private constructor to hide the implicit public one. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1118)
1. MAJOR [Log4JRemover.java#L61](https://github.com/ow2-proactive/scheduling/blob/e06826a5ae9bf38c3a462a031662b49109d0757f/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L61): Introduce a new variable instead of reusing the parameter "hierarchy". [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1226)
1. MAJOR [Log4JRemover.java#L67](https://github.com/ow2-proactive/scheduling/blob/e06826a5ae9bf38c3a462a031662b49109d0757f/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L67): Replace the synchronized class "Hashtable" by an unsynchronized one such as "HashMap". [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1149)
1. MAJOR [TaskLogger.java#L82](https://github.com/ow2-proactive/scheduling/blob/e06826a5ae9bf38c3a462a031662b49109d0757f/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L82): Rename field "taskLogger" [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1700)
1. MAJOR [TaskLogger.java#L102](https://github.com/ow2-proactive/scheduling/blob/e06826a5ae9bf38c3a462a031662b49109d0757f/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L102): Rename "taskLogger" which hides the field declared at line 82. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. MAJOR [SchedulingService.java#L491](https://github.com/ow2-proactive/scheduling/blob/e06826a5ae9bf38c3a462a031662b49109d0757f/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulingService.java#L491): Rename "jobs" which hides the field declared at line 88. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. MINOR [Log4JRemover.java#L44](https://github.com/ow2-proactive/scheduling/blob/e06826a5ae9bf38c3a462a031662b49109d0757f/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L44): Make the "logger" logger private static final. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1312)
1. MINOR [TaskLogger.java#L31](https://github.com/ow2-proactive/scheduling/blob/e06826a5ae9bf38c3a462a031662b49109d0757f/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L31): Remove this unused import 'java.lang.reflect.Constructor'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [TaskLogger.java#L32](https://github.com/ow2-proactive/scheduling/blob/e06826a5ae9bf38c3a462a031662b49109d0757f/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L32): Remove this unused import 'java.lang.reflect.Field'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [TaskLogger.java#L33](https://github.com/ow2-proactive/scheduling/blob/e06826a5ae9bf38c3a462a031662b49109d0757f/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L33): Remove this unused import 'java.util.Hashtable'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 19 issues
* MAJOR 6 major
* MINOR 13 minor

#### Top 10 issues

1. MAJOR [Log4JRemover.java#L42](https://github.com/ow2-proactive/scheduling/blob/a5ff77689ec2f57cf05328845fa8243a382b7011/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L42): Add a private constructor to hide the implicit public one. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1118)
1. MAJOR [Log4JRemover.java#L61](https://github.com/ow2-proactive/scheduling/blob/a5ff77689ec2f57cf05328845fa8243a382b7011/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L61): Introduce a new variable instead of reusing the parameter "hierarchy". [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1226)
1. MAJOR [Log4JRemover.java#L67](https://github.com/ow2-proactive/scheduling/blob/a5ff77689ec2f57cf05328845fa8243a382b7011/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L67): Replace the synchronized class "Hashtable" by an unsynchronized one such as "HashMap". [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1149)
1. MAJOR [TaskLogger.java#L82](https://github.com/ow2-proactive/scheduling/blob/a5ff77689ec2f57cf05328845fa8243a382b7011/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L82): Rename field "taskLogger" [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1700)
1. MAJOR [TaskLogger.java#L102](https://github.com/ow2-proactive/scheduling/blob/a5ff77689ec2f57cf05328845fa8243a382b7011/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L102): Rename "taskLogger" which hides the field declared at line 82. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. MAJOR [SchedulingService.java#L492](https://github.com/ow2-proactive/scheduling/blob/a5ff77689ec2f57cf05328845fa8243a382b7011/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulingService.java#L492): Rename "jobs" which hides the field declared at line 89. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. MINOR [Log4JRemover.java#L44](https://github.com/ow2-proactive/scheduling/blob/a5ff77689ec2f57cf05328845fa8243a382b7011/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/util/logforwarder/Log4JRemover.java#L44): Make the "logger" logger private static final. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1312)
1. MINOR [TaskLogger.java#L31](https://github.com/ow2-proactive/scheduling/blob/a5ff77689ec2f57cf05328845fa8243a382b7011/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L31): Remove this unused import 'java.lang.reflect.Constructor'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [TaskLogger.java#L32](https://github.com/ow2-proactive/scheduling/blob/a5ff77689ec2f57cf05328845fa8243a382b7011/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L32): Remove this unused import 'java.lang.reflect.Field'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [TaskLogger.java#L33](https://github.com/ow2-proactive/scheduling/blob/a5ff77689ec2f57cf05328845fa8243a382b7011/scheduler/scheduler-node/src/main/java/org/ow2/proactive/scheduler/task/TaskLogger.java#L33): Remove this unused import 'java.util.Hashtable'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

**Pull request merged**
