### PR TITLE
Improve logging in TaskProActiveDataspaces

### PR DESCRIPTION
**Pull request by fviale**
- add times needed to find files, transfer files, mount dataspaces, etc

### CODE REVIEW

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 68 issues
* MINOR 68 minor

#### Top 10 issues

1. MINOR [SchedulerFrontend.java#L372](https://github.com/ow2-proactive/scheduling/blob/ff353b609639d3b90ca8364aff3bee4168e80c16/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L372): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L404](https://github.com/ow2-proactive/scheduling/blob/ff353b609639d3b90ca8364aff3bee4168e80c16/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L404): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L414](https://github.com/ow2-proactive/scheduling/blob/ff353b609639d3b90ca8364aff3bee4168e80c16/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L414): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L425](https://github.com/ow2-proactive/scheduling/blob/ff353b609639d3b90ca8364aff3bee4168e80c16/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L425): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L460](https://github.com/ow2-proactive/scheduling/blob/ff353b609639d3b90ca8364aff3bee4168e80c16/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L460): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L470](https://github.com/ow2-proactive/scheduling/blob/ff353b609639d3b90ca8364aff3bee4168e80c16/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L470): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L480](https://github.com/ow2-proactive/scheduling/blob/ff353b609639d3b90ca8364aff3bee4168e80c16/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L480): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L487](https://github.com/ow2-proactive/scheduling/blob/ff353b609639d3b90ca8364aff3bee4168e80c16/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L487): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L509](https://github.com/ow2-proactive/scheduling/blob/ff353b609639d3b90ca8364aff3bee4168e80c16/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L509): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L519](https://github.com/ow2-proactive/scheduling/blob/ff353b609639d3b90ca8364aff3bee4168e80c16/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L519): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 68 issues
* MINOR 68 minor

#### Top 10 issues

1. MINOR [SchedulerFrontend.java#L372](https://github.com/ow2-proactive/scheduling/blob/6d361efc0217911bb9b2f802bcb9524a09750dd0/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L372): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L404](https://github.com/ow2-proactive/scheduling/blob/6d361efc0217911bb9b2f802bcb9524a09750dd0/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L404): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L414](https://github.com/ow2-proactive/scheduling/blob/6d361efc0217911bb9b2f802bcb9524a09750dd0/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L414): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L425](https://github.com/ow2-proactive/scheduling/blob/6d361efc0217911bb9b2f802bcb9524a09750dd0/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L425): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L460](https://github.com/ow2-proactive/scheduling/blob/6d361efc0217911bb9b2f802bcb9524a09750dd0/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L460): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L470](https://github.com/ow2-proactive/scheduling/blob/6d361efc0217911bb9b2f802bcb9524a09750dd0/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L470): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L480](https://github.com/ow2-proactive/scheduling/blob/6d361efc0217911bb9b2f802bcb9524a09750dd0/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L480): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L487](https://github.com/ow2-proactive/scheduling/blob/6d361efc0217911bb9b2f802bcb9524a09750dd0/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L487): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L509](https://github.com/ow2-proactive/scheduling/blob/6d361efc0217911bb9b2f802bcb9524a09750dd0/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L509): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L519](https://github.com/ow2-proactive/scheduling/blob/6d361efc0217911bb9b2f802bcb9524a09750dd0/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L519): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 68 issues
* MINOR 68 minor

#### Top 10 issues

1. MINOR [SchedulerFrontend.java#L372](https://github.com/ow2-proactive/scheduling/blob/70f7a4b5f573c83a1c8ebbc74313918edf7702bd/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L372): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L404](https://github.com/ow2-proactive/scheduling/blob/70f7a4b5f573c83a1c8ebbc74313918edf7702bd/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L404): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L414](https://github.com/ow2-proactive/scheduling/blob/70f7a4b5f573c83a1c8ebbc74313918edf7702bd/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L414): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L425](https://github.com/ow2-proactive/scheduling/blob/70f7a4b5f573c83a1c8ebbc74313918edf7702bd/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L425): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L460](https://github.com/ow2-proactive/scheduling/blob/70f7a4b5f573c83a1c8ebbc74313918edf7702bd/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L460): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L470](https://github.com/ow2-proactive/scheduling/blob/70f7a4b5f573c83a1c8ebbc74313918edf7702bd/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L470): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L480](https://github.com/ow2-proactive/scheduling/blob/70f7a4b5f573c83a1c8ebbc74313918edf7702bd/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L480): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L487](https://github.com/ow2-proactive/scheduling/blob/70f7a4b5f573c83a1c8ebbc74313918edf7702bd/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L487): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L509](https://github.com/ow2-proactive/scheduling/blob/70f7a4b5f573c83a1c8ebbc74313918edf7702bd/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L509): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L519](https://github.com/ow2-proactive/scheduling/blob/70f7a4b5f573c83a1c8ebbc74313918edf7702bd/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L519): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

**Comment by fviale** [comment]
Retest this please

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 68 issues
* MINOR 68 minor

#### Top 10 issues

1. MINOR [SchedulerFrontend.java#L372](https://github.com/ow2-proactive/scheduling/blob/ef2874089749c44dda9ec41774affb0406e59b74/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L372): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L404](https://github.com/ow2-proactive/scheduling/blob/ef2874089749c44dda9ec41774affb0406e59b74/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L404): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L414](https://github.com/ow2-proactive/scheduling/blob/ef2874089749c44dda9ec41774affb0406e59b74/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L414): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L425](https://github.com/ow2-proactive/scheduling/blob/ef2874089749c44dda9ec41774affb0406e59b74/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L425): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L460](https://github.com/ow2-proactive/scheduling/blob/ef2874089749c44dda9ec41774affb0406e59b74/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L460): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L470](https://github.com/ow2-proactive/scheduling/blob/ef2874089749c44dda9ec41774affb0406e59b74/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L470): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L480](https://github.com/ow2-proactive/scheduling/blob/ef2874089749c44dda9ec41774affb0406e59b74/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L480): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L487](https://github.com/ow2-proactive/scheduling/blob/ef2874089749c44dda9ec41774affb0406e59b74/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L487): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L509](https://github.com/ow2-proactive/scheduling/blob/ef2874089749c44dda9ec41774affb0406e59b74/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L509): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulerFrontend.java#L519](https://github.com/ow2-proactive/scheduling/blob/ef2874089749c44dda9ec41774affb0406e59b74/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulerFrontend.java#L519): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

**Comment by fviale** [comment]
Retest this please

**Pull request merged**
