### PR TITLE
Skip OS Name test

### PR DESCRIPTION
**Pull request by tobwiens**
Skip OS Name test

What does this test test?:
It seems that the test gets os.name (System.getProperty) and takes it as a regular expression.
Then the test gets os.name (System.getProperty) again and matches that against the regular expression.

Problem:
Windows Server 2016 return Windows NT (unknown)
"(unknown)" is not interpreted as a simple string because the brackets are not escaped
Matching against the same string fails.

Solution:
Ignoring the test for now

### CODE REVIEW

**Comment by tobwiens** [comment]
Retest this please

**Comment by tobwiens** [comment]
@ow2-proactive/developers two reviews please.

**Comment by lpellegr** [comment]
@tobwiens Why not fixing the test by escaping the String with [Pattern#quote](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#quote(java.lang.String))?

**Comment by tobwiens** [comment]
@lpellegr Very good! Thank you!

**Comment by fviale** [comment]
@tobwiens Why not fixing actually the SelectionUtils.checkOSName() method by escaping the String with Pattern.quote ?

**Comment by lpellegr** [comment]
@fviale I don't think it is a good idea to escape the String inside `SelectionUtils#checkOSName()`. This will break backwards compatibility and prevent users to use regular expressions.

**Comment by fviale** [comment]
@lpellegr , my mistake, if it's supposed to accept regular expressions, then I agree

**Comment by tobwiens** [comment]
Restest this please

**Comment by tobwiens** [comment]
Retest this please

**Comment by tobwiens** [comment]
Retest this please

**Pull request merged**
