### PR TITLE
prevent the submission of nameless job

### PR DESCRIPTION
**Pull request by Aminelouati**

### CODE REVIEW

**Comment by paraita** [comment]
Good. One question though, how does it behave with the job name " " ? Is that a valid job name ?

**Comment by amouhoub** [comment]
@paraita it takes a freaky mind to think about freaky situations !!!
What about if the name is "THE BEST CRAZY WORKFLOW EVER" ?

**Comment by Aminelouati** [comment]
@paraita it is a bug :D

**Comment by paraita** [comment]
the `" "` case don't necessarily need to be included in this PR, we can put it as an inprovement in the issues tab anyway :)

**Pull request merged**
