### PR TITLE
Remove the credential from the rm-node lib.

### PR DESCRIPTION
**Pull request by tobwiens**
Remove the credential from the rm-node lib.

This removes the rm.cred file from the node.jar.

### CODE REVIEW

**Comment by tobwiens** [comment]
Retest this

**Comment by tobwiens** [comment]
Test this

**Comment by tobwiens** [comment]
Retest this please

**Comment by fviale** [comment]
Same remark as the other pull request, here you delete the file. All changes should be done in a single pull request

**Comment by tobwiens** [comment]
The other PR https://github.com/ow2-proactive/scheduling/pull/2574 was done 5 days ago. I fixed an issue at that point and did not know what else I will discover or how I will solve that problem. 

I did the fix so I submitted a PR, otherwise I would have thrown the changes away (Probably being forgotten in my git log in some branch).

**Comment by tobwiens** [comment]
@ow2-proactive/developers Two reviews please: Question does removing the rm.cred affect anything else than the node.jar?

**Comment by lpellegr** [comment]
have you checked ProActive agents?

**Comment by mbenguig** [comment]
ok

**Comment by tobwiens** [comment]
@lpellegr Thank you, I will check PA-Agents

**Comment by tobwiens** [comment]
Can't install the Agent
image

**Pull request merged**
