### PR TITLE
Add Postgres stored procedure example for housekeeping

### PR DESCRIPTION
**Pull request by lpellegr**
as requested by Brian

### CODE REVIEW

**Comment by lpellegr** [comment]
@ow2-proactive/developers Could two people please review the changes?

**Comment by tobwiens** [comment]
Looks good :+1:, good explanation of the code and config setting. 
Can we guard this with tests somehow? Or can we put this somewhere aside. I think that might outdated soon and we won't remove it. 
What is your opinion on that??

**Comment by lpellegr** [comment]
@tobwiens This is an example working with 6.0.5 only. It is already outdated since the data model changed between version 6 and 7. I already made the same comment to Brian but he wants to have the example to be included in the release.

**Comment by lpellegr** [comment]
I forgot to mention that it is planned to write performance tests soon but they will not be against version 6.0.X.

**Comment by mbenguig** [comment]
ok for me.

**Pull request merged**
