### PR TITLE
fix for #2920 Scheduling unit tests hangs on linux

### PR DESCRIPTION
**Pull request by fviale**
Move several unit tests to functional tests as these tests either
- start ProActive objects which can leave non-daemon threads
- start a web server
- take a huge amount of time for a unit test (all db-related tests)

### CODE REVIEW

**Comment by fviale** [comment]
Retest this please

**Comment by fviale** [comment]
Retest this please

**Comment by fviale** [comment]
Retest this please

**Comment by fviale** [comment]
Retest this please

**Comment by fviale** [comment]
Retest this please

**Comment by MaelAudren** [comment]
retest this please

**Comment by fviale** [comment]
retest this please

**Comment by fviale** [comment]
Retest this please

**Comment by fviale** [comment]
retest this please

**Pull request merged**
