### PR TITLE
handle empty passwords

### PR DESCRIPTION
**Pull request by fviale**
as we observed a case where an empty password could wrongly allow arbitrary connections from user to some AD server, we need to prevent empty passwords in the ldap module code.

### CODE REVIEW

**Review by amouhoub — APPROVED** [review]

**Review by nebilbenmabrouk — APPROVED** [review]
LGTM, I hope that no one will use accidently the same password as the Fake password :)

**Comment by fviale** [comment]
@nebilbenmabrouk hope so too but I estimate 1 chance on 1 billion :-)

**Review by MaelAudren — COMMENTED** [review]
That would be better if this could configurable by the sysadmin. As Github is open source it would be easy for a hacker to find out the password and to test it with an account.

**Comment by MaelAudren** [comment]
Instead of sending an emtpy password with ldap which could allow the connection. A bad password will be sent which will ensure that the password check is done.

**Pull request merged**
