### PR TITLE
Allow execution of server side workflows

### PR DESCRIPTION
**Pull request by mauriciojost**
This commit enable the Scheduler REST API to be able to create jobs
using workflows that are retrieved from HTTP servers.
Also makes the Studio REST API expose workflow and template contents
(provided valid credentials).
Consequently, now it is possible to create a workflow (or template)
using the Studio, get its URL, and create with it (and additional
variables if needed) a new job resource on the Scheduler REST API. It
will automatically perform authentication and downloading of the
workflow, and then submission.

### CODE REVIEW

**Comment by mauriciojost** [comment]
@youribonnaffe Could you take a look please?

**Comment by mauriciojost** [comment]
Dear bot, retest this please .

**Comment by lpellegr** [comment]
retest this please

**Comment by lpellegr** [comment]
Dear bot, retest this please .

**Comment by youribonnaffe** [comment]
Pretty please bobot, test this please.

**Comment by youribonnaffe** [comment]
Try again bobot to rebuild this please

**Comment by youribonnaffe** [comment]
test this please

**Comment by youribonnaffe** [comment]
test this bitte

**Comment by youribonnaffe** [comment]
test this please

**Comment by youribonnaffe** [comment]
:+1:

**Pull request merged**
