### PR TITLE
fixes issue #2660

### PR DESCRIPTION
**Pull request by sophiesongge**
fixes issue #2660

### CODE REVIEW

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 2 issues

1. MAJOR [SetInfrastructureCommand.java#L123](https://github.com/ow2-proactive/scheduling/blob/84a488911a4346d4838608288f67b2ff4f9047d2/rest/rest-cli/src/main/java/org/ow2/proactive_grid_cloud_portal/cli/cmd/rm/SetInfrastructureCommand.java#L123): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS134)
1. MAJOR [SetInfrastructureCommand.java#L123](https://github.com/ow2-proactive/scheduling/blob/84a488911a4346d4838608288f67b2ff4f9047d2/rest/rest-cli/src/main/java/org/ow2/proactive_grid_cloud_portal/cli/cmd/rm/SetInfrastructureCommand.java#L123): Move the "" string literal on the left side of this string comparison. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1132)

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 1 issue

1. MAJOR [SetInfrastructureCommand.java#L123](https://github.com/ow2-proactive/scheduling/blob/39974bdc905e93abcc1dfca76e922b23f65ef862/rest/rest-cli/src/main/java/org/ow2/proactive_grid_cloud_portal/cli/cmd/rm/SetInfrastructureCommand.java#L123): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS134)

**Comment by sophiesongge** [comment]
retest this please

**Comment by sophiesongge** [comment]
retest this please

**Pull request merged**
