### PR TITLE
org.ow2.proactive_grid_cloud_portal.cli.utils.ExceptionUtility replac…

### PR DESCRIPTION
**Pull request by mbenguig**
…ed by com.google.common.base.Throwables.getStackTraceAsString

### CODE REVIEW

**Comment by marcocast** [comment]
👍  Good job removing custom code. If you want you can also do :

import static com.google.common.base.Throwables.getStackTraceAsString;

and use it without the Throwables class.

**Comment by mbenguig** [comment]
Maybe it could be interesting to remove/replace all Formatter.stackTraceToString occurences..

**Comment by mbenguig** [comment]
Same thing for StackTraceUtil.getStackTrace

**Comment by mbenguig** [comment]
Same thing for org.ow2.proactive.scheduler.rest.ExceptionUtility.getStackTrace

**Comment by mbenguig** [comment]
Same thing for org.ow2.proactive.resourcemanager.nodesource.infrastructure.Utils.getStacktrace
I think it was the last one.

**Comment by lpellegr** [comment]
:+1:

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 4 issues:
* MINOR 4 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Remove this unused import 'java.io.PrintWriter'.](https://github.com/ow2-proactive/scheduling/blob/82a39b4d21aa6e22a25daca869cacb9efae177de/rest/rest-client/src/main/java/org/ow2/proactive/scheduler/rest/ExceptionUtility.java#L37) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AUselessImportCheck)
* MINOR [Remove this unused import 'java.io.StringWriter'.](https://github.com/ow2-proactive/scheduling/blob/82a39b4d21aa6e22a25daca869cacb9efae177de/rest/rest-client/src/main/java/org/ow2/proactive/scheduler/rest/ExceptionUtility.java#L38) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AUselessImportCheck)
* MINOR [Remove this unused import 'java.io.StringWriter'.](https://github.com/ow2-proactive/scheduling/blob/82a39b4d21aa6e22a25daca869cacb9efae177de/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/nodesource/infrastructure/Utils.java#L45) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AUselessImportCheck)
* MINOR [Remove this unused import 'java.io.PrintWriter'.](https://github.com/ow2-proactive/scheduling/blob/82a39b4d21aa6e22a25daca869cacb9efae177de/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/nodesource/infrastructure/Utils.java#L44) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AUselessImportCheck)

**Pull request merged**
