### PR TITLE
Add a property to shorten job submission logging

### PR DESCRIPTION
**Pull request by bamedro**
Add a property to shorten job submission logging, by removing tasks details.

With large jobs (>500 tasks), this logging can slow down the scheduler, taking several minutes to produce this logging information.

### CODE REVIEW

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [InternalJob.java#L398](https://github.com/ow2-proactive/scheduling/blob/90d3eb370232739ca6fadf2c44b583c86f11831e/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/job/InternalJob.java#L398): Add a default case to this switch. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ASwitchLastCaseIsDefaultCheck)
1. ![MAJOR][MAJOR] [PASchedulerProperties.java#L421](https://github.com/ow2-proactive/scheduling/blob/90d3eb370232739ca6fadf2c44b583c86f11831e/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/core/properties/PASchedulerProperties.java#L421): Remove this unused private "PASchedulerProperties" constructor. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [PASchedulerProperties.java#L432](https://github.com/ow2-proactive/scheduling/blob/90d3eb370232739ca6fadf2c44b583c86f11831e/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/core/properties/PASchedulerProperties.java#L432): Remove this unused private "PASchedulerProperties" constructor. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by fviale** [comment]
Actually, would it not make sense to use a dedicated logger instead of defining a new property ?
This way, it would be easy to deactivate this logger.

**Comment by Mykhailenko** [comment]
Retest this please

**Comment by Mykhailenko** [comment]
Retest this please

**Pull request merged**
