### PR TITLE
Do not remove job vars after job is finished

### PR DESCRIPTION
**Pull request by Mykhailenko**
https://github.com/ow2-proactive/scheduling/issues/3330

### CODE REVIEW

**Comment by fviale** [comment]
Can you double-check that the variables are removed from the DB when the job is removed ?

**Comment by Mykhailenko** [comment]
@fviale you are right. With this PR vars will remain forever (until housekeeping launches).

So I will remove vars when LiveJobs::removeJob is called

**Comment by fviale** [comment]
@Mykhailenko isn't housekeeping doing the same as removeJob ?
If removeJob does not remove entries, I double housekeeping would.

**Comment by Mykhailenko** [comment]
@fviale could you look again. I move single line, before we were removing vars when job become finished, but now it will be removed only when whole job is removed. Are you ok with it?

**Pull request merged**
