### PR TITLE
fix for #2971 While pausing a job, tasks can fail to start

### PR DESCRIPTION
**Pull request by fviale**
- make InternalJob, InternalTask thread safe by synchonizing all public methods and defensive copy of collections
 - In SchedulingMethodImpl, before starting a task, verify that it is not paused

### CODE REVIEW

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 10 issues

1. MAJOR [JobDescriptorImpl.java#L739](https://github.com/ow2-proactive/scheduling/blob/515dc4eeb9af3229480dc5ca2da53a35a1a81ff5/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/descriptor/JobDescriptorImpl.java#L739): Remove usage of generic wildcard type. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1452)
1. MINOR [JobState.java#L113](https://github.com/ow2-proactive/scheduling/blob/515dc4eeb9af3229480dc5ca2da53a35a1a81ff5/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/job/JobState.java#L113): Reorder the modifiers to comply with the Java Language Specification. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)
1. MINOR [JobState.java#L122](https://github.com/ow2-proactive/scheduling/blob/515dc4eeb9af3229480dc5ca2da53a35a1a81ff5/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/job/JobState.java#L122): Reorder the modifiers to comply with the Java Language Specification. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)
1. MINOR [TaskState.java#L157](https://github.com/ow2-proactive/scheduling/blob/515dc4eeb9af3229480dc5ca2da53a35a1a81ff5/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/task/TaskState.java#L157): Reorder the modifiers to comply with the Java Language Specification. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)
1. MINOR [TaskState.java#L166](https://github.com/ow2-proactive/scheduling/blob/515dc4eeb9af3229480dc5ca2da53a35a1a81ff5/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/task/TaskState.java#L166): Reorder the modifiers to comply with the Java Language Specification. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)
1. MINOR [JobDescriptorImpl.java#L39](https://github.com/ow2-proactive/scheduling/blob/515dc4eeb9af3229480dc5ca2da53a35a1a81ff5/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/descriptor/JobDescriptorImpl.java#L39): Remove this unused import 'java.util.concurrent.ConcurrentHashMap'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [InternalJob.java#L39](https://github.com/ow2-proactive/scheduling/blob/515dc4eeb9af3229480dc5ca2da53a35a1a81ff5/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/job/InternalJob.java#L39): Remove this unused import 'java.util.concurrent.ConcurrentHashMap'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [InternalTask.java#L925](https://github.com/ow2-proactive/scheduling/blob/515dc4eeb9af3229480dc5ca2da53a35a1a81ff5/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/task/internal/InternalTask.java#L925): Reorder the modifiers to comply with the Java Language Specification. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)
1. MINOR [InternalTask.java#L946](https://github.com/ow2-proactive/scheduling/blob/515dc4eeb9af3229480dc5ca2da53a35a1a81ff5/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/task/internal/InternalTask.java#L946): Reorder the modifiers to comply with the Java Language Specification. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)
1. MINOR [InternalTask.java#L961](https://github.com/ow2-proactive/scheduling/blob/515dc4eeb9af3229480dc5ca2da53a35a1a81ff5/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/task/internal/InternalTask.java#L961): Reorder the modifiers to comply with the Java Language Specification. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)

**Comment by marcocast** [comment]
It seems strange we need to Synchronise all those methods. I'm a bit scared about performance degradation and possible deadlocks....

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 11 issues
* MAJOR 2 major
* MINOR 9 minor

#### Top 10 issues

1. MAJOR [CommonAttribute.java#L208](https://github.com/ow2-proactive/scheduling/blob/57293614b72760fdb1d1f1e37c14af37bda46448/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/task/CommonAttribute.java#L208): Return an empty collection instead of null. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1168)
1. MAJOR [JobDescriptorImpl.java#L739](https://github.com/ow2-proactive/scheduling/blob/57293614b72760fdb1d1f1e37c14af37bda46448/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/descriptor/JobDescriptorImpl.java#L739): Remove usage of generic wildcard type. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1452)
1. MINOR [JobState.java#L113](https://github.com/ow2-proactive/scheduling/blob/57293614b72760fdb1d1f1e37c14af37bda46448/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/job/JobState.java#L113): Reorder the modifiers to comply with the Java Language Specification. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)
1. MINOR [JobState.java#L122](https://github.com/ow2-proactive/scheduling/blob/57293614b72760fdb1d1f1e37c14af37bda46448/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/job/JobState.java#L122): Reorder the modifiers to comply with the Java Language Specification. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)
1. MINOR [Task.java#L30](https://github.com/ow2-proactive/scheduling/blob/57293614b72760fdb1d1f1e37c14af37bda46448/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/task/Task.java#L30): Remove this unused import 'java.util.HashMap'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [TaskState.java#L157](https://github.com/ow2-proactive/scheduling/blob/57293614b72760fdb1d1f1e37c14af37bda46448/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/task/TaskState.java#L157): Reorder the modifiers to comply with the Java Language Specification. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)
1. MINOR [TaskState.java#L166](https://github.com/ow2-proactive/scheduling/blob/57293614b72760fdb1d1f1e37c14af37bda46448/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/task/TaskState.java#L166): Reorder the modifiers to comply with the Java Language Specification. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)
1. MINOR [JobDescriptorImpl.java#L39](https://github.com/ow2-proactive/scheduling/blob/57293614b72760fdb1d1f1e37c14af37bda46448/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/descriptor/JobDescriptorImpl.java#L39): Remove this unused import 'java.util.concurrent.ConcurrentHashMap'. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [InternalTask.java#L925](https://github.com/ow2-proactive/scheduling/blob/57293614b72760fdb1d1f1e37c14af37bda46448/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/task/internal/InternalTask.java#L925): Reorder the modifiers to comply with the Java Language Specification. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)
1. MINOR [InternalTask.java#L946](https://github.com/ow2-proactive/scheduling/blob/57293614b72760fdb1d1f1e37c14af37bda46448/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/task/internal/InternalTask.java#L946): Reorder the modifiers to comply with the Java Language Specification. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 35 issues
* MAJOR 14 major
* MINOR 21 minor

#### Top 10 issues

1. MAJOR [CommonAttribute.java#L236](https://github.com/ow2-proactive/scheduling/blob/3e229306a2032bbb7bfc7939e8ef25e82274ce69/scheduler/scheduler-api/src/main/java/org/ow2/proactive/scheduler/common/task/CommonAttribute.java#L236): Return an empty collection instead of null. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1168)
1. MAJOR [JobDescriptorImpl.java#L432](https://github.com/ow2-proactive/scheduling/blob/3e229306a2032bbb7bfc7939e8ef25e82274ce69/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/descriptor/JobDescriptorImpl.java#L432): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS134)
1. MAJOR [JobDescriptorImpl.java#L488](https://github.com/ow2-proactive/scheduling/blob/3e229306a2032bbb7bfc7939e8ef25e82274ce69/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/descriptor/JobDescriptorImpl.java#L488): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS134)
1. MAJOR [JobDescriptorImpl.java#L849](https://github.com/ow2-proactive/scheduling/blob/3e229306a2032bbb7bfc7939e8ef25e82274ce69/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/descriptor/JobDescriptorImpl.java#L849): Remove usage of generic wildcard type. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1452)
1. MAJOR [InternalJob.java#L87](https://github.com/ow2-proactive/scheduling/blob/3e229306a2032bbb7bfc7939e8ef25e82274ce69/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/job/InternalJob.java#L87): The Cyclomatic Complexity of this class is 228 which is greater than 200 authorized. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AClassCyclomaticComplexity)
1. MAJOR [InternalJob.java#L206](https://github.com/ow2-proactive/scheduling/blob/3e229306a2032bbb7bfc7939e8ef25e82274ce69/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/job/InternalJob.java#L206): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS134)
1. MAJOR [InternalJob.java#L741](https://github.com/ow2-proactive/scheduling/blob/3e229306a2032bbb7bfc7939e8ef25e82274ce69/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/job/InternalJob.java#L741): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS134)
1. MAJOR [InternalJob.java#L760](https://github.com/ow2-proactive/scheduling/blob/3e229306a2032bbb7bfc7939e8ef25e82274ce69/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/job/InternalJob.java#L760): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS134)
1. MAJOR [InternalJob.java#L965](https://github.com/ow2-proactive/scheduling/blob/3e229306a2032bbb7bfc7939e8ef25e82274ce69/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/job/InternalJob.java#L965): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS134)
1. MAJOR [InternalJob.java#L1390](https://github.com/ow2-proactive/scheduling/blob/3e229306a2032bbb7bfc7939e8ef25e82274ce69/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/job/InternalJob.java#L1390): Remove usage of generic wildcard type. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1452)

**Pull request closed without merging**
