### PR TITLE
Remove updateJobInSchedulerState

### PR DESCRIPTION
**Pull request by Mykhailenko**

### CODE REVIEW

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [LiveJobs.java#L696](https://github.com/ow2-proactive/scheduling/blob/e89b4c9adaacf02c665d8413d7e140ef296c354c/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L696): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. ![MINOR][MINOR] [LiveJobs.java#L782](https://github.com/ow2-proactive/scheduling/blob/e89b4c9adaacf02c665d8413d7e140ef296c354c/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L782): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. ![MINOR][MINOR] [LiveJobs.java#L837](https://github.com/ow2-proactive/scheduling/blob/e89b4c9adaacf02c665d8413d7e140ef296c354c/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L837): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. ![MINOR][MINOR] [LiveJobs.java#L873](https://github.com/ow2-proactive/scheduling/blob/e89b4c9adaacf02c665d8413d7e140ef296c354c/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L873): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Mykhailenko** [comment]
Retest this please

**Comment by Mykhailenko** [comment]
Retest this please

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [LiveJobs.java#L696](https://github.com/ow2-proactive/scheduling/blob/7bda05d6ea4d88c8e35f9324108484e6bbd4a84c/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L696): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. ![MINOR][MINOR] [LiveJobs.java#L782](https://github.com/ow2-proactive/scheduling/blob/7bda05d6ea4d88c8e35f9324108484e6bbd4a84c/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L782): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. ![MINOR][MINOR] [LiveJobs.java#L837](https://github.com/ow2-proactive/scheduling/blob/7bda05d6ea4d88c8e35f9324108484e6bbd4a84c/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L837): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. ![MINOR][MINOR] [LiveJobs.java#L873](https://github.com/ow2-proactive/scheduling/blob/7bda05d6ea4d88c8e35f9324108484e6bbd4a84c/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L873): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
