### PR TITLE
SchedulingMethodImpl : don't hold the locks on jobs to be scheduled d…

### PR DESCRIPTION
**Pull request by fviale**
…uring the complete scheduling loop

- lock jobs only when selecting tasks to be scheduled, then unlock them
- lock job atomically when starting a task
- use ConcurrentHashMap in InternalJob for keeping tasks

### CODE REVIEW

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 9 issues

1. MINOR [LiveJobs.java#L676](https://github.com/ow2-proactive/scheduling/blob/37e3d83f8bbd1927ee93e4063750374b75914f1a/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L676): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [LiveJobs.java#L763](https://github.com/ow2-proactive/scheduling/blob/37e3d83f8bbd1927ee93e4063750374b75914f1a/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L763): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [LiveJobs.java#L818](https://github.com/ow2-proactive/scheduling/blob/37e3d83f8bbd1927ee93e4063750374b75914f1a/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L818): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [LiveJobs.java#L854](https://github.com/ow2-proactive/scheduling/blob/37e3d83f8bbd1927ee93e4063750374b75914f1a/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L854): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulingService.java#L573](https://github.com/ow2-proactive/scheduling/blob/37e3d83f8bbd1927ee93e4063750374b75914f1a/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulingService.java#L573): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulingService.java#L605](https://github.com/ow2-proactive/scheduling/blob/37e3d83f8bbd1927ee93e4063750374b75914f1a/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulingService.java#L605): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulingService.java#L637](https://github.com/ow2-proactive/scheduling/blob/37e3d83f8bbd1927ee93e4063750374b75914f1a/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulingService.java#L637): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulingService.java#L667](https://github.com/ow2-proactive/scheduling/blob/37e3d83f8bbd1927ee93e4063750374b75914f1a/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulingService.java#L667): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulingService.java#L695](https://github.com/ow2-proactive/scheduling/blob/37e3d83f8bbd1927ee93e4063750374b75914f1a/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulingService.java#L695): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

**Comment by fviale** [comment]
Retest this please

**Comment by fviale** [comment]
Restest this please

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 9 issues

1. MINOR [LiveJobs.java#L676](https://github.com/ow2-proactive/scheduling/blob/283e85a3026791b0b1da80a074c3f8a9b252856d/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L676): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [LiveJobs.java#L763](https://github.com/ow2-proactive/scheduling/blob/283e85a3026791b0b1da80a074c3f8a9b252856d/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L763): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [LiveJobs.java#L818](https://github.com/ow2-proactive/scheduling/blob/283e85a3026791b0b1da80a074c3f8a9b252856d/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L818): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [LiveJobs.java#L854](https://github.com/ow2-proactive/scheduling/blob/283e85a3026791b0b1da80a074c3f8a9b252856d/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L854): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulingService.java#L573](https://github.com/ow2-proactive/scheduling/blob/283e85a3026791b0b1da80a074c3f8a9b252856d/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulingService.java#L573): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulingService.java#L605](https://github.com/ow2-proactive/scheduling/blob/283e85a3026791b0b1da80a074c3f8a9b252856d/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulingService.java#L605): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulingService.java#L637](https://github.com/ow2-proactive/scheduling/blob/283e85a3026791b0b1da80a074c3f8a9b252856d/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulingService.java#L637): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulingService.java#L667](https://github.com/ow2-proactive/scheduling/blob/283e85a3026791b0b1da80a074c3f8a9b252856d/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulingService.java#L667): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. MINOR [SchedulingService.java#L695](https://github.com/ow2-proactive/scheduling/blob/283e85a3026791b0b1da80a074c3f8a9b252856d/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/SchedulingService.java#L695): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

**Pull request merged**
