### PR TITLE
add perl task dependency with configurations for perl execution

### PR DESCRIPTION
**Pull request by ShatalovYaroslav**
Connected with https://github.com/ow2-proactive/jsr223-perl/pull/1

### CODE REVIEW

**Comment by ShatalovYaroslav** [comment]
retest this please

**Comment by tobwiens** [comment]
retest this please

**Comment by MaelAudren** [comment]
retest this please

**Comment by MaelAudren** [comment]
retest this pls

**Comment by MaelAudren** [comment]
retest this please

**Comment by MaelAudren** [comment]
retest this please

**Comment by ShatalovYaroslav** [comment]
retest this please

**Comment by ShatalovYaroslav** [comment]
retest this please

**Comment by ShatalovYaroslav** [comment]
retest this please

**Pull request merged**
