### PR TITLE
Nodes Recovery

### PR DESCRIPTION
**Pull request by jrochas**
Recover nodes state for all infrastructures.
Cloud Azure included

### CODE REVIEW

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 48 issues
* MAJOR 30 major
* MINOR 18 minor

#### Top 10 issues

1. MAJOR [RMCore.java#L486](https://github.com/ow2-proactive/scheduling/blob/0884f7f9c2e6f14d783679901b69d0fbb3f8c7c0/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/core/RMCore.java#L486): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [NodeSourceData.java#L69](https://github.com/ow2-proactive/scheduling/blob/0884f7f9c2e6f14d783679901b69d0fbb3f8c7c0/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/NodeSourceData.java#L69): Make "infrastructureVariables" transient or serializable. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1948)
1. MAJOR [RMDBManager.java#L310](https://github.com/ow2-proactive/scheduling/blob/0884f7f9c2e6f14d783679901b69d0fbb3f8c7c0/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L310): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L325](https://github.com/ow2-proactive/scheduling/blob/0884f7f9c2e6f14d783679901b69d0fbb3f8c7c0/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L325): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L377](https://github.com/ow2-proactive/scheduling/blob/0884f7f9c2e6f14d783679901b69d0fbb3f8c7c0/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L377): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L393](https://github.com/ow2-proactive/scheduling/blob/0884f7f9c2e6f14d783679901b69d0fbb3f8c7c0/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L393): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L411](https://github.com/ow2-proactive/scheduling/blob/0884f7f9c2e6f14d783679901b69d0fbb3f8c7c0/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L411): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L427](https://github.com/ow2-proactive/scheduling/blob/0884f7f9c2e6f14d783679901b69d0fbb3f8c7c0/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L427): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L447](https://github.com/ow2-proactive/scheduling/blob/0884f7f9c2e6f14d783679901b69d0fbb3f8c7c0/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L447): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L463](https://github.com/ow2-proactive/scheduling/blob/0884f7f9c2e6f14d783679901b69d0fbb3f8c7c0/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L463): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)

**Comment by jrochas** [comment]
retest this please

**Comment by jrochas** [comment]
retest this please

**Comment by jrochas** [comment]
retest this please

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 578 issues
* CRITICAL 1 critical
* MAJOR 33 major
* MINOR 544 minor

#### Top 10 issues

1. CRITICAL [InfrastructureManager.java#L419](https://github.com/ow2-proactive/scheduling/blob/5fbcc71fa2df14d2c0cf6615f62995b07e302d0a/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/nodesource/infrastructure/InfrastructureManager.java#L419): Use a logger to log this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1148)
1. MAJOR [RMCore.java#L486](https://github.com/ow2-proactive/scheduling/blob/5fbcc71fa2df14d2c0cf6615f62995b07e302d0a/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/core/RMCore.java#L486): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [NodeSourceData.java#L69](https://github.com/ow2-proactive/scheduling/blob/5fbcc71fa2df14d2c0cf6615f62995b07e302d0a/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/NodeSourceData.java#L69): Make "infrastructureVariables" transient or serializable. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1948)
1. MAJOR [RMDBManager.java#L310](https://github.com/ow2-proactive/scheduling/blob/5fbcc71fa2df14d2c0cf6615f62995b07e302d0a/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L310): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L325](https://github.com/ow2-proactive/scheduling/blob/5fbcc71fa2df14d2c0cf6615f62995b07e302d0a/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L325): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L377](https://github.com/ow2-proactive/scheduling/blob/5fbcc71fa2df14d2c0cf6615f62995b07e302d0a/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L377): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L393](https://github.com/ow2-proactive/scheduling/blob/5fbcc71fa2df14d2c0cf6615f62995b07e302d0a/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L393): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L411](https://github.com/ow2-proactive/scheduling/blob/5fbcc71fa2df14d2c0cf6615f62995b07e302d0a/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L411): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L427](https://github.com/ow2-proactive/scheduling/blob/5fbcc71fa2df14d2c0cf6615f62995b07e302d0a/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L427): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L447](https://github.com/ow2-proactive/scheduling/blob/5fbcc71fa2df14d2c0cf6615f62995b07e302d0a/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L447): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 578 issues
* CRITICAL 1 critical
* MAJOR 33 major
* MINOR 544 minor

#### Top 10 issues

1. CRITICAL [InfrastructureManager.java#L419](https://github.com/ow2-proactive/scheduling/blob/ef203855f0948a5c7647c9807fddc0610e5511ad/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/nodesource/infrastructure/InfrastructureManager.java#L419): Use a logger to log this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1148)
1. MAJOR [RMCore.java#L486](https://github.com/ow2-proactive/scheduling/blob/ef203855f0948a5c7647c9807fddc0610e5511ad/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/core/RMCore.java#L486): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [NodeSourceData.java#L69](https://github.com/ow2-proactive/scheduling/blob/ef203855f0948a5c7647c9807fddc0610e5511ad/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/NodeSourceData.java#L69): Make "infrastructureVariables" transient or serializable. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1948)
1. MAJOR [RMDBManager.java#L310](https://github.com/ow2-proactive/scheduling/blob/ef203855f0948a5c7647c9807fddc0610e5511ad/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L310): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L325](https://github.com/ow2-proactive/scheduling/blob/ef203855f0948a5c7647c9807fddc0610e5511ad/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L325): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L377](https://github.com/ow2-proactive/scheduling/blob/ef203855f0948a5c7647c9807fddc0610e5511ad/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L377): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L393](https://github.com/ow2-proactive/scheduling/blob/ef203855f0948a5c7647c9807fddc0610e5511ad/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L393): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L411](https://github.com/ow2-proactive/scheduling/blob/ef203855f0948a5c7647c9807fddc0610e5511ad/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L411): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L427](https://github.com/ow2-proactive/scheduling/blob/ef203855f0948a5c7647c9807fddc0610e5511ad/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L427): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L447](https://github.com/ow2-proactive/scheduling/blob/ef203855f0948a5c7647c9807fddc0610e5511ad/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L447): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 577 issues
* CRITICAL 1 critical
* MAJOR 33 major
* MINOR 543 minor

#### Top 10 issues

1. CRITICAL [InfrastructureManager.java#L419](https://github.com/ow2-proactive/scheduling/blob/01da8e4c404593ac331723c810a7c74e98f5bfe4/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/nodesource/infrastructure/InfrastructureManager.java#L419): Use a logger to log this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1148)
1. MAJOR [RMCore.java#L486](https://github.com/ow2-proactive/scheduling/blob/01da8e4c404593ac331723c810a7c74e98f5bfe4/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/core/RMCore.java#L486): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [NodeSourceData.java#L69](https://github.com/ow2-proactive/scheduling/blob/01da8e4c404593ac331723c810a7c74e98f5bfe4/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/NodeSourceData.java#L69): Make "infrastructureVariables" transient or serializable. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1948)
1. MAJOR [RMDBManager.java#L310](https://github.com/ow2-proactive/scheduling/blob/01da8e4c404593ac331723c810a7c74e98f5bfe4/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L310): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L325](https://github.com/ow2-proactive/scheduling/blob/01da8e4c404593ac331723c810a7c74e98f5bfe4/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L325): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L377](https://github.com/ow2-proactive/scheduling/blob/01da8e4c404593ac331723c810a7c74e98f5bfe4/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L377): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L393](https://github.com/ow2-proactive/scheduling/blob/01da8e4c404593ac331723c810a7c74e98f5bfe4/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L393): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L411](https://github.com/ow2-proactive/scheduling/blob/01da8e4c404593ac331723c810a7c74e98f5bfe4/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L411): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L427](https://github.com/ow2-proactive/scheduling/blob/01da8e4c404593ac331723c810a7c74e98f5bfe4/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L427): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [RMDBManager.java#L447](https://github.com/ow2-proactive/scheduling/blob/01da8e4c404593ac331723c810a7c74e98f5bfe4/rm/rm-server/src/main/java/org/ow2/proactive/resourcemanager/db/RMDBManager.java#L447): Either log or rethrow this exception. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1166)

**Pull request merged**
