### PR TITLE
Job submission with variables from CLI does not work with Java 8

### LINKED ISSUE #2252: Job submission with variables from CLI does not work with Java 8
If a submission of a job, with variables, is performed from interactive CLI, using Java 8, it will fail with the following error:
> $> submit('job.xml', [foo='bar'])
> Cannot cast jdk.internal.dynalink.beans.StaticClass to java.lang.Class

Probably an issue with Nashorn that is now used with Java 8.

### PR DESCRIPTION
**Pull request by cdiop**
Modification of submit command syntax
```submit('pathWorkflow.xml', "var1=value1 var2=value2")```

This pull-request closes #2252.

### CODE REVIEW

**Comment by fviale** [comment]
what if we need that var1=value with space   ?

**Comment by fviale** [comment]
I mean var1 = "value with space"

**Comment by cdiop** [comment]
I keep the same syntax 
-s,--submit <job-descriptor [var1=value1 var2=value2 …]>

and I remove the [ ]

We can replace the space by , or ;

**Comment by fviale** [comment]
Ideally in non interactive mode, I would see something like :

proactive-client -s ... var1="value1" var2="value2"

But I don't know how argument are parsed (and especially across different
OS shells) and how that would translate in interactive mode.

**Comment by cdiop** [comment]
The syntax is now:
submit('job.xml', '{"var1":"value1","var2":"value2"}') with possibiulity to have space

**Comment by fviale** [comment]
I think it's a bit "heavy"

why switching from "=" to ":" ? I would prefer to choose the syntax
collectively, other people might have elegant ideas

**Comment by fviale** [comment]
I suppose it's kind of tricky as the argument is parsed as a whole and
split into tokens

**Comment by fviale** [comment]
ah that's a JSON syntax maybe ? Then in that case, yes it makes sense.

**Comment by marcocast** [comment]
Yes, it is pure json format

**Comment by cdiop** [comment]
retest this please

**Comment by fviale** [comment]
How will be the syntax from the CLI in non-interactive mode ?

**Comment by cdiop** [comment]
Could two people please review the changes?

**Comment by cdiop** [comment]
retest this please

**Comment by cdiop** [comment]
Retest this please.

**Comment by cdiop** [comment]
Retest this please

**Comment by lpellegr** [comment]
@cdiop I have added some suggestions.

**Comment by cdiop** [comment]
Retest this please

**Comment by cdiop** [comment]
Retest this please.

**Comment by cdiop** [comment]
Retest this please.

**Comment by cdiop** [comment]
Retest this please

**Comment by lpellegr** [comment]
Retest this please

**Comment by lpellegr** [comment]
Retest this please

**Pull request merged**
