### PR TITLE
Add 'Restart All In-Error tasks' test

### PR DESCRIPTION
**Pull request by Mykhailenko**
Test which reproduces this [issue](https://github.com/ow2-proactive/scheduling/issues/3308)

### CODE REVIEW

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [LiveJobs.java#L703](https://github.com/ow2-proactive/scheduling/blob/685485a26323599586d4cd75ce44491fdfba48d3/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L703): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. ![MINOR][MINOR] [LiveJobs.java#L786](https://github.com/ow2-proactive/scheduling/blob/685485a26323599586d4cd75ce44491fdfba48d3/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L786): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. ![MINOR][MINOR] [LiveJobs.java#L841](https://github.com/ow2-proactive/scheduling/blob/685485a26323599586d4cd75ce44491fdfba48d3/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L841): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. ![MINOR][MINOR] [LiveJobs.java#L877](https://github.com/ow2-proactive/scheduling/blob/685485a26323599586d4cd75ce44491fdfba48d3/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L877): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [LiveJobs.java#L703](https://github.com/ow2-proactive/scheduling/blob/8412b433cbe92b9a180aecc90023237dab53b93b/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L703): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. ![MINOR][MINOR] [LiveJobs.java#L786](https://github.com/ow2-proactive/scheduling/blob/8412b433cbe92b9a180aecc90023237dab53b93b/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L786): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. ![MINOR][MINOR] [LiveJobs.java#L841](https://github.com/ow2-proactive/scheduling/blob/8412b433cbe92b9a180aecc90023237dab53b93b/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L841): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. ![MINOR][MINOR] [LiveJobs.java#L877](https://github.com/ow2-proactive/scheduling/blob/8412b433cbe92b9a180aecc90023237dab53b93b/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L877): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sophiesongge** [comment]
@fviale In this case it will not change a running job's status. Because this method is only called when we restart the in-error tasks. The purpose of this method is to change the job's status from 'Paused' to 'In-Error', but when there is no 'In-Error' tasks, there is no reason to put the job's status to 'In-Error'. That's why I check it here whether there's in-error tasks, if not, then I change the job's status from 'Paused' to 'Pending', and 'Running' will be automatically changed when the job is running.

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [LiveJobs.java#L701](https://github.com/ow2-proactive/scheduling/blob/27a78452f3ec6afc8b777d0a88f4ab32810926ef/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L701): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. ![MINOR][MINOR] [LiveJobs.java#L784](https://github.com/ow2-proactive/scheduling/blob/27a78452f3ec6afc8b777d0a88f4ab32810926ef/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L784): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. ![MINOR][MINOR] [LiveJobs.java#L839](https://github.com/ow2-proactive/scheduling/blob/27a78452f3ec6afc8b777d0a88f4ab32810926ef/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L839): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)
1. ![MINOR][MINOR] [LiveJobs.java#L875](https://github.com/ow2-proactive/scheduling/blob/27a78452f3ec6afc8b777d0a88f4ab32810926ef/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/LiveJobs.java#L875): Remove the redundant '!unknownSymbol!' thrown exception declaration(s). [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
