### PR TITLE
gradle.build refactor

### PR DESCRIPTION
**Pull request by marcocast**
Splitting gradle.build in subprojects  dedicated builds

### CODE REVIEW

**Comment by lpellegr** [comment]
@marcocast I don't know why you have closed your previous pull-request to recreate a similar one but for information you can push force your changes into your fork (`git push -f`), thus avoiding to create new pull-requests if you want to completely change your commits.

Pull-requests can be closed but not removed. It's better to avoid history pollution when possible.

**Comment by marcocast** [comment]
My mistake and thanks for noticing it.

**Comment by marcocast** [comment]
retest please

**Comment by marcocast** [comment]
Can one more person review these changes?

**Comment by paraita** [comment]
Good for me !

**Comment by marcocast** [comment]
Retest this please.

**Pull request merged**
