### PR TITLE
new plannings resource in scheduling api to transfer planned job to job planner

### PR DESCRIPTION
**Pull request by yinan-liu**

### CODE REVIEW

**Comment by tobwiens** [comment]
When you check for checkAccess, will this be automatically granted or to do you need to white list "plannings" somewhere?

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 5 issues

1. CRITICAL [PortalConfiguration.java#L68](https://github.com/ow2-proactive/scheduling/blob/3952cac863f5eb1a7798e9f75dd87b1cf2fb6af8/rest/rest-server/src/main/java/org/ow2/proactive_grid_cloud_portal/webapp/PortalConfiguration.java#L68): Make this "public static JOBPLANNER_URL" field final [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1444)
1. MAJOR [SchedulerStateRest.java#L2343](https://github.com/ow2-proactive/scheduling/blob/3952cac863f5eb1a7798e9f75dd87b1cf2fb6af8/rest/rest-server/src/main/java/org/ow2/proactive_grid_cloud_portal/scheduler/SchedulerStateRest.java#L2343): Add the "@Override" annotation above this method signature [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1161)
1. MAJOR [PortalConfiguration.java#L68](https://github.com/ow2-proactive/scheduling/blob/3952cac863f5eb1a7798e9f75dd87b1cf2fb6af8/rest/rest-server/src/main/java/org/ow2/proactive_grid_cloud_portal/webapp/PortalConfiguration.java#L68): Make JOBPLANNER_URL a static final constant or non-public and provide accessors if needed. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. MINOR [SchedulerRestInterface.java#L1221](https://github.com/ow2-proactive/scheduling/blob/3952cac863f5eb1a7798e9f75dd87b1cf2fb6af8/rest/rest-api/src/main/java/org/ow2/proactive_grid_cloud_portal/common/SchedulerRestInterface.java#L1221): Refactor this method to throw at most one checked exception instead of: org.ow2.proactive_grid_cloud_portal.scheduler.exception.JobCreationRestException, org.ow2.proactive_grid_cloud_portal.scheduler.exception.NotConnectedRestException, org.ow2.proactive_grid_cloud_portal.scheduler.exception.PermissionRestException, org.ow2.proactive_grid_cloud_portal.scheduler.exception.SubmissionClosedRestException, java.io.IOException [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1160)
1. MINOR [StudioInterface.java#L220](https://github.com/ow2-proactive/scheduling/blob/3952cac863f5eb1a7798e9f75dd87b1cf2fb6af8/rest/rest-api/src/main/java/org/ow2/proactive_grid_cloud_portal/studio/StudioInterface.java#L220): Refactor this method to throw at most one checked exception instead of: org.ow2.proactive_grid_cloud_portal.scheduler.exception.JobCreationRestException, org.ow2.proactive_grid_cloud_portal.scheduler.exception.NotConnectedRestException, org.ow2.proactive_grid_cloud_portal.scheduler.exception.PermissionRestException, org.ow2.proactive_grid_cloud_portal.scheduler.exception.SubmissionClosedRestException, java.io.IOException [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1160)

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 5 issues

1. CRITICAL [PortalConfiguration.java#L68](https://github.com/ow2-proactive/scheduling/blob/3cb3842b3b7251918d43cc3998193c230d04e845/rest/rest-server/src/main/java/org/ow2/proactive_grid_cloud_portal/webapp/PortalConfiguration.java#L68): Make this "public static JOBPLANNER_URL" field final [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1444)
1. MAJOR [SchedulerStateRest.java#L2343](https://github.com/ow2-proactive/scheduling/blob/3cb3842b3b7251918d43cc3998193c230d04e845/rest/rest-server/src/main/java/org/ow2/proactive_grid_cloud_portal/scheduler/SchedulerStateRest.java#L2343): Add the "@Override" annotation above this method signature [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1161)
1. MAJOR [PortalConfiguration.java#L68](https://github.com/ow2-proactive/scheduling/blob/3cb3842b3b7251918d43cc3998193c230d04e845/rest/rest-server/src/main/java/org/ow2/proactive_grid_cloud_portal/webapp/PortalConfiguration.java#L68): Make JOBPLANNER_URL a static final constant or non-public and provide accessors if needed. [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. MINOR [SchedulerRestInterface.java#L1221](https://github.com/ow2-proactive/scheduling/blob/3cb3842b3b7251918d43cc3998193c230d04e845/rest/rest-api/src/main/java/org/ow2/proactive_grid_cloud_portal/common/SchedulerRestInterface.java#L1221): Refactor this method to throw at most one checked exception instead of: org.ow2.proactive_grid_cloud_portal.scheduler.exception.JobCreationRestException, org.ow2.proactive_grid_cloud_portal.scheduler.exception.NotConnectedRestException, org.ow2.proactive_grid_cloud_portal.scheduler.exception.PermissionRestException, org.ow2.proactive_grid_cloud_portal.scheduler.exception.SubmissionClosedRestException, java.io.IOException [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1160)
1. MINOR [StudioInterface.java#L220](https://github.com/ow2-proactive/scheduling/blob/3cb3842b3b7251918d43cc3998193c230d04e845/rest/rest-api/src/main/java/org/ow2/proactive_grid_cloud_portal/studio/StudioInterface.java#L220): Refactor this method to throw at most one checked exception instead of: org.ow2.proactive_grid_cloud_portal.scheduler.exception.JobCreationRestException, org.ow2.proactive_grid_cloud_portal.scheduler.exception.NotConnectedRestException, org.ow2.proactive_grid_cloud_portal.scheduler.exception.PermissionRestException, org.ow2.proactive_grid_cloud_portal.scheduler.exception.SubmissionClosedRestException, java.io.IOException [rule](http://master.ci.activeeon.com:9000/coding_rules#rule_key=squid%3AS1160)

**Comment by paraita** [comment]
retest this please

**Pull request merged**
