### PR TITLE
Add the scheduledAt date to the filtering search criteria

### PR DESCRIPTION
**Pull request by paraita**

### CODE REVIEW

**Comment by marcocast** [comment]
looks ok 2 me

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 3 issues:
* MAJOR 3 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [Method has 8 parameters, which is greater than 7 authorized.](https://github.com/ow2-proactive/scheduling/blob/bc2604f66f2c18d8d20b0643642617ef33c8126d/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/db/TaskDBUtils.java#L145) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00107)
* MAJOR [Add a private constructor to hide the implicit public one.](https://github.com/ow2-proactive/scheduling/blob/bc2604f66f2c18d8d20b0643642617ef33c8126d/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/db/TaskDBUtils.java#L56) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1118)
* MAJOR [Reduce this anonymous class number of lines from 24 to at most 20, or make it a named class.](https://github.com/ow2-proactive/scheduling/blob/bc2604f66f2c18d8d20b0643642617ef33c8126d/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/db/TaskDBUtils.java#L59) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1188)

**Comment by tobwiens** [comment]
Is ok

**Comment by marcocast** [comment]
retest this please

**Pull request merged**
