### PR TITLE
Add filters to rm rest models

### PR DESCRIPTION
**Pull request by fviale**
Allows filtering:
 - node sources based on infrastructure type or name regular expression
 - hosts (name regular expression)
 - tokens (name regular expression)

### CODE REVIEW

**Review by andrewssobral — APPROVED** [review]

**Comment by mboussaa** [comment]
Why not based on the policy ?

**Review by oanaBiancaSchiopu — APPROVED** [review]

**Comment by fviale** [comment]
@mboussaa I could add a filter on the policy yes, but I could not find any use case for it.

**Comment by mboussaa** [comment]
Use case is to show me all static or all Dynamic node sources

**Comment by fviale** [comment]
@mboussaa ok I will add it

**Review by mboussaa — APPROVED** [review]

**Pull request merged**
