### PR TITLE
Some proactive-client options are broken

### PR DESCRIPTION
**Pull request by lpellegr**
Linked with https://github.com/ow2-proactive/programming/pull/1306.

### CODE REVIEW

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
@ow2-proactive/developers Could two people please review the changes?

**Comment by paraita** [comment]
:+1:

**Comment by lpellegr** [comment]
Retest this please.

**Pull request merged**
