### PR TITLE
Display instructions to use debug mode on error

### LINKED ISSUE #1946: Display instructions to use debug mode on error
<a href="https://jira.activeeon.com/browse/SCHEDULING-2181" title="SCHEDULING-2181">Original issue</a> created by <a href="mailto:fabien.viale_AT_activeeon.com">Fabien Viale</a> on 25, Sep 2014 at 14:53 PM - SCHEDULING-2181

<hr />

*No description*

### PR DESCRIPTION
**Pull request by lpellegr**
This patch closes #1946.

### CODE REVIEW

**Comment by lpellegr** [comment]
Retest this please.

**Comment by lpellegr** [comment]
@ow2-proactive/developers Could two developers please review the changes?

**Comment by tobwiens** [comment]
Looks good.

**Comment by marcocast** [comment]
I think bug fixing is the only real opportunity we have to refactor code and improve coverage. I doubt there will ever be a dedicated story to refactor code that is working as expected. But if it is too complex, yes, I agree with you and it needs to be properly planned and pushed.

**Comment by lpellegr** [comment]
It depends how priorities are defined. It seems the priority is release 7.0.0. We have a dedicated Epic for defining _release pipeline_. Why would it not be possible to have Epic for improving code coverage, etc?

I don't think it is a good idea to put unrelated changes together. It is just make understanding complex and bugs hard to identify.

**Comment by fviale** [comment]
seems ok to me

**Pull request merged**
